name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # GitHub Secrets에서 값을 가져와 env.js 생성
      - name: Generate env.js
        run: |
          echo "export const API_KEY = \"${{ secrets.API_KEY }}\";" > env.js
          echo "export const SERVICE_ID = \"${{ secrets.SERVICE_ID }}\";" >> env.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 현재 디렉토리 전체를 업로드
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
